language:
    java
jdk:
    - oraclejdk8
install:
    mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    mvn test -P !build-extras -B
cache:
    directories:
        - ~/.m2/repository
after_success:
    - mvn clean test jacoco:report coveralls:report
    - .travis/before-deploy.sh
    - .travis/deploy.sh
